spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true


